# Name: Jamal Amro  
Module: Big Data for Enterprise  
Assignment: PRAC1 – Task 2

# Task 2.1 — MongoDB Setup

In [1]:
# Import pandas for data handling and analysis
import pandas as pd

# Import MongoClient to connect Python with MongoDB
from pymongo import MongoClient

# Task 2.2 — Loading Data and Preparation

In [2]:
# Load the World Cup dataset from CSV file into a DataFrame
df = pd.read_csv("WorldCupMatches.csv")

# Display first 5 rows to verify successful loading
df.head()

,Year,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,Attendance,HalftimeHomeGoals,HalftimeAwayGoals,Referee,Assistant1,Assistant2,RoundID,MatchID,HomeTeamInitials,AwayTeamInitials
0,1982,Group 3,Camp Nou,Barcelona,Argentina,0,1,Belgium,95000.0,0,0,CHRISTOV Vojtech (TCH),PALOTAI Karoly (HUN),JARGUZ Alojzy (POL),293,749,ARG,BEL
1,1982,Group 1,Estadio Municipal de BalaÔøΩdos,Vigo,Italy,0,0,Poland,33000.0,0,0,VAUTROT Michel (FRA),PROKOP Adolf (GDR),RAINEA Nicolae (ROU),293,995,ITA,POL
2,1982,Group 6,Ramon Sanchez Pizjuan,Seville,Brazil,2,1,Soviet Union,68000.0,0,1,LAMO CASTILLO Augusto (ESP),SANCHEZ ARMINIO Victoriano (ESP),GARCIA CARRION Jose L. (ESP),293,791,BRA,URS
3,1982,Group 1,Riazor,La CoruÔøΩA,Peru,0,0,Cameroon,11000.0,0,0,WOEHRER Franz (AUT),RAINEA Nicolae (ROU),PROKOP Adolf (GDR),293,833,PER,CMR
4,1982,Group 3,Nuevo Estadio,Elche,Hungary,10,1,El Salvador,23000.0,3,0,AL DOY Ebrahim (BHR),CORVER Charles (NED),LUND-SORENSEN Henning (DEN),293,896,HUN,SLV

In [3]:
# Display structure and data types of dataset
df.info()

# Check for missing values in each column
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 544 entries, 0 to 543
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               544 non-null    int64
 1   Stage              544 non-null    str
 2   Stadium            544 non-null    str
 3   City               544 non-null    str
 4   HomeTeamName       544 non-null    str
 5   HomeTeamGoals      544 non-null    int64
 6   AwayTeamGoals      544 non-null    int64
 7   AwayTeamName       544 non-null    str
 8   Attendance         542 non-null    float64
 9   HalftimeHomeGoals  544 non-null    int64
 10  HalftimeAwayGoals  544 non-null    int64
 11  Referee            544 non-null    str
 12  Assistant1         544 non-null    str
 13  Assistant2         544 non-null    str
 14  RoundID            544 non-null    int64
 15  MatchID            544 non-null    int64
 16  HomeTeamInitials   544 non-null    str
 17  AwayTeamInitials   544 non-null    str
dtypes: float64(1), int64(7), str(10)
memory usage: 141.2 KB

Year                 0
Stage                0
Stadium              0
City                 0
HomeTeamName         0
HomeTeamGoals        0
AwayTeamGoals        0
AwayTeamName         0
Attendance           2
HalftimeHomeGoals    0
HalftimeAwayGoals    0
Referee              0
Assistant1           0
Assistant2           0
RoundID              0
MatchID              0
HomeTeamInitials     0
AwayTeamInitials     0
dtype: int64

In [4]:
#check dataset columns
df.columns

Index(['Year', 'Stage', 'Stadium', 'City', 'HomeTeamName', 'HomeTeamGoals',
       'AwayTeamGoals', 'AwayTeamName', 'Attendance', 'HalftimeHomeGoals',
       'HalftimeAwayGoals', 'Referee', 'Assistant1', 'Assistant2', 'RoundID',
       'MatchID', 'HomeTeamInitials', 'AwayTeamInitials'],
      dtype='str')

In [5]:
# Check duplicates based on MatchID
df.duplicated(subset=["MatchID"]).sum()

np.int64(16)

In [6]:
# Show duplicated rows
df[df.duplicated(subset=["MatchID"], keep=False)]

,Year,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,Attendance,HalftimeHomeGoals,HalftimeAwayGoals,Referee,Assistant1,Assistant2,RoundID,MatchID,HomeTeamInitials,AwayTeamInitials
512,2014,Round of 16,Estadio Mineirao,Belo Horizonte,Brazil,1,1,Chile,57714.0,0,0,WEBB Howard (ENG),MULLARKEY Michael (ENG),Darren CANN (ENG),255951,300186487,BRA,CHI
513,2014,Round of 16,Estadio do Maracana,Rio De Janeiro,Colombia,2,0,Uruguay,73804.0,1,0,BjÔøΩrn KUIPERS (NED),Sander VAN ROEKEL (NED),Erwin ZEINSTRA (NED),255951,300186491,COL,URU
514,2014,Round of 16,Estadio Nacional,Brasilia,France,2,0,Nigeria,67882.0,0,0,GEIGER Mark (USA),HURD Sean (USA),FLETCHER Joe (CAN),255951,300186462,FRA,NGA
515,2014,Round of 16,Estadio Beira-Rio,Porto Alegre,Germany,2,1,Algeria,NaN,0,0,RICCI Sandro (BRA),DE CARVALHO Emerson (BRA),VAN GASSE Marcelo (BRA),255951,300186460,GER,ALG
516,2014,Quarter-finals,Estadio Castelao,Fortaleza,Brazil,2,1,Colombia,60342.0,1,0,Carlos VELASCO CARBALLO (ESP),ALONSO FERNANDEZ Roberto (ESP),YUSTE Juan (ESP),255953,300186461,BRA,COL
517,2014,Quarter-finals,Estadio do Maracana,Rio De Janeiro,France,0,1,Germany,74240.0,0,1,PITANA Nestor (ARG),MAIDANA Hernan (ARG),BELATTI Juan Pablo (ARG),255953,300186485,FRA,GER
518,2014,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,58141.0,0,5,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955,300186474,BRA,GER
519,2014,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
520,2014,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG
521,2014,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,63267.0,0,0,CÔøΩneyt ÔøΩAKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
522,2014,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,51179.0,0,0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953,300186488,NED,CRC
523,2014,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1,0,Belgium,68551.0,1,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255953,300186504,ARG,BEL
524,2014,Round of 16,Estadio Castelao,Fortaleza,Netherlands,2,1,Mexico,58817.0,0,0,PROENCA Pedro (POR),MIRANDA Bertino (POR),TRIGO Jose (POR),255951,300186508,NED,MEX
525,2014,Round of 16,Arena Pernambuco,Recife,Costa Rica,1,1,Greece,41242.0,0,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255951,300186459,CRC,GRE
526,2014,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1,0,Switzerland,63255.0,0,0,ERIKSSON Jonas (SWE),KLASENIUS Mathias (SWE),WARNMARK Daniel (SWE),255951,300186503,ARG,SUI
527,2014,Round of 16,Arena Fonte Nova,Salvador,Belgium,2,1,USA,51227.0,0,0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255951,300186497,BEL,USA
528,2014,Round of 16,Estadio Mineirao,Belo Horizonte,Brazil,1,1,Chile,57714.0,0,0,WEBB Howard (ENG),MULLARKEY Michael (ENG),Darren CANN (ENG),255951,300186487,BRA,CHI
529,2014,Round of 16,Estadio do Maracana,Rio De Janeiro,Colombia,2,0,Uruguay,73804.0,1,0,BjÔøΩrn KUIPERS (NED),Sander VAN ROEKEL (NED),Erwin ZEINSTRA (NED),255951,300186491,COL,URU
530,2014,Round of 16,Estadio Castelao,Fortaleza,Netherlands,2,1,Mexico,58817.0,0,0,PROENCA Pedro (POR),MIRANDA Bertino (POR),TRIGO Jose (POR),255951,300186508,NED,MEX
531,2014,Round of 16,Arena Pernambuco,Recife,Costa Rica,1,1,Greece,41242.0,0,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255951,300186459,CRC,GRE
532,2014,Round of 16,Estadio Nacional,Brasilia,France,2,0,Nigeria,67882.0,0,0,GEIGER Mark (USA),HURD Sean (USA),FLETCHER Joe (CAN),255951,300186462,FRA,NGA
533,2014,Round of 16,Estadio Beira-Rio,Porto Alegre,Germany,2,1,Algeria,NaN,0,0,RICCI Sandro (BRA),DE CARVALHO Emerson (BRA),VAN GASSE Marcelo (BRA),255951,300186460,GER,ALG
534,2014,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1,0,Switzerland,63255.0,0,0,ERIKSSON Jonas (SWE),KLASENIUS Mathias (SWE),WARNMARK Daniel (SWE),255951,300186503,ARG,SUI
535,2014,Round of 16,Arena Fonte Nova,Salvador,Belgium,2,1,USA,51227.0,0,0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255951,300186497,BEL,USA
536,2014,Quarter-finals,Estadio do Maracana,Rio De Janeiro,France,0,1,Germany,74240.0,0,1,PITANA Nestor (ARG),MAIDANA Hernan (ARG),BELATTI Juan Pablo (ARG),255953,300186485,FRA,GER
537,2014,Quarter-finals,Estadio Castelao,Fortaleza,Brazil,2,1,Colombia,60342.0,1,0,Carlos VELASCO CARBALLO (ESP),ALONSO FERNANDEZ Roberto (ESP),YUSTE Juan (ESP),255953,300186461,BRA,COL
538,2014,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1,0,Belgium,68551.0,1,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255953,300186504,ARG,BEL
539,2014,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,51179.0,0,0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953,300186488,NED,CRC
540,2014,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,58141.0,0,5,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955,300186474,BRA,GER
541,2014,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,63267.0,0,0,CÔøΩneyt ÔøΩAKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
542,2014,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
543,2014,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

In [7]:
# Remove duplicates based on MatchID (keep first occurrence)
df_clean = df.drop_duplicates(subset=["MatchID"], keep="first")

In [8]:
df_clean.duplicated(subset=["MatchID"]).sum()

np.int64(0)

In [9]:
# !pip install pymongo  i already installed via CMD

In [10]:
# collection.delete_many({})   i use it just when i need to delete the loaded dataset to mongo

In [11]:
# Establish connection to local MongoDB server
client = MongoClient("mongodb://localhost:27017/")

# Create (or access) database named 'worldcup_db'
db = client["worldcup_db"]

# Create (or access) collection named 'matches'
collection = db["matches"]

print("Connected to MongoDB successfully!")

Connected to MongoDB successfully!

In [12]:
# Convert DataFrame into list of dictionaries (MongoDB documents)
data = df_clean.to_dict(orient="records")

# Display one sample document
print(data[0])

{'Year': 1982, 'Stage': 'Group 3', 'Stadium': 'Camp Nou', 'City': 'Barcelona ', 'HomeTeamName': 'Argentina', 'HomeTeamGoals': 0, 'AwayTeamGoals': 1, 'AwayTeamName': 'Belgium', 'Attendance': 95000.0, 'HalftimeHomeGoals': 0, 'HalftimeAwayGoals': 0, 'Referee': 'CHRISTOV Vojtech (TCH)', 'Assistant1': 'PALOTAI Karoly (HUN)', 'Assistant2': 'JARGUZ Alojzy (POL)', 'RoundID': 293, 'MatchID': 749, 'HomeTeamInitials': 'ARG', 'AwayTeamInitials': 'BEL'}

In [13]:
# Insert all documents into MongoDB collection
collection.insert_many(data)

print("Dataset inserted into MongoDB successfully!")

Dataset inserted into MongoDB successfully!

![MongoDB Screenshot](MongoConnectoin1.png)

In [14]:
# Count number of documents inserted
collection.count_documents({})

528

The process began by importing the required libraries, where Pandas was used for data handling and PyMongo for database interaction. The World Cup dataset was then loaded into a Pandas DataFrame, enabling structured data analysis. Basic exploration was performed to understand the dataset structure and identify missing values, highlighting the need for a flexible data model. A connection to MongoDB was established, and a database with a collection was created. Finally, the dataset was converted into JSON-like documents, making it suitable for storage in MongoDB’s document-oriented structure

In [15]:
# Insert 5 additional documents into the MongoDB collection
# Some fields are intentionally missing to demonstrate MongoDB schema flexibility

collection.insert_many([
    
    # Document 1: Missing some fields (e.g., Stadium, Referee)
    {
        "Year": 2026,
        "Stage": "Group",
        "HomeTeamName": "Libya",
        "AwayTeamName": "Brazil",
        "HomeTeamGoals": 2
    },

    # Document 2: Missing goal-related fields
    {
        "Year": 2026,
        "Stage": "Quarter-finals",
        "HomeTeamName": "Egypt",
        "AwayTeamName": "France"
    },

    # Document 3: Missing multiple attributes
    {
        "Year": 2026,
        "Stage": "Semi-finals",
        "HomeTeamName": "England",
        "AwayTeamName": "Morocco"
    },

    # Document 4: Minimal data (only few fields provided)
    {
        "Year": 2026,
        "Stage": "Final",
        "HomeTeamGoals": 3
    },

    # Document 5: Missing team names
    {
        "Year": 2026,
        "Stage": "Group",
        "AwayTeamGoals": 1
    }

])

print("5 additional documents inserted successfully!")

5 additional documents inserted successfully!

![MongoDB Screenshot](MongoConnectoinDocuments2.png)

The five additional documents were inserted with some missing fields to demonstrate MongoDB’s ability to handle flexible and semi-structured data. Unlike relational databases, MongoDB does not require a fixed schema, allowing documents with varying structures to be stored efficiently

# TASK 2.3 — MongoDB Queries

## Query 1: Quarter-final matches

In [16]:
# Retrieve all matches where Stage is 'Quarter-finals'
for doc in collection.find({"Stage": "Quarter-finals"}).limit(5):
    print(doc)

{'_id': ObjectId('69cd0b1d5116547190fa1305'), 'Year': 1986, 'Stage': 'Quarter-finals', 'Stadium': 'Jalisco', 'City': 'Guadalajara ', 'HomeTeamName': 'Brazil', 'HomeTeamGoals': 1, 'AwayTeamGoals': 1, 'AwayTeamName': 'France', 'Attendance': 65000.0, 'HalftimeHomeGoals': 0, 'HalftimeAwayGoals': 0, 'Referee': 'IGNA Ioan (ROU)', 'Assistant1': 'NEMETH Lajos (HUN)', 'Assistant2': 'CHRISTOV Vojtech (TCH)', 'RoundID': 714, 'MatchID': 440, 'HomeTeamInitials': 'BRA', 'AwayTeamInitials': 'FRA'}
{'_id': ObjectId('69cd0b1d5116547190fa1306'), 'Year': 1986, 'Stage': 'Quarter-finals', 'Stadium': 'Estadio Universitario', 'City': 'Monterrey ', 'HomeTeamName': 'Germany FR', 'HomeTeamGoals': 0, 'AwayTeamGoals': 0, 'AwayTeamName': 'Mexico', 'Attendance': 41700.0, 'HalftimeHomeGoals': 0, 'HalftimeAwayGoals': 0, 'Referee': 'DIAZ PALACIO Jesus (COL)', 'Assistant1': 'BAMBRIDGE Christopher (AUS)', 'Assistant2': 'SNODDY Alan (NIR)', 'RoundID': 714, 'MatchID': 575, 'HomeTeamInitials': 'FRG', 'AwayTeamInitials': 'MEX'}
{'_id': ObjectId('69cd0b1d5116547190fa1307'), 'Year': 1986, 'Stage': 'Quarter-finals', 'Stadium': 'Cuauhtemoc', 'City': 'Puebla ', 'HomeTeamName': 'Spain', 'HomeTeamGoals': 1, 'AwayTeamGoals': 1, 'AwayTeamName': 'Belgium', 'Attendance': 45000.0, 'HalftimeHomeGoals': 0, 'HalftimeAwayGoals': 0, 'Referee': 'KIRSCHEN Siegfried (GER)', 'Assistant1': 'CODESAL MENDEZ Edgardo (MEX)', 'Assistant2': 'BRUMMEIER Horst (AUT)', 'RoundID': 714, 'MatchID': 421, 'HomeTeamInitials': 'ESP', 'AwayTeamInitials': 'BEL'}
{'_id': ObjectId('69cd0b1d5116547190fa1308'), 'Year': 1986, 'Stage': 'Quarter-finals', 'Stadium': 'Estadio Azteca', 'City': 'Mexico City ', 'HomeTeamName': 'Argentina', 'HomeTeamGoals': 2, 'AwayTeamGoals': 1, 'AwayTeamName': 'England', 'Attendance': 114580.0, 'HalftimeHomeGoals': 0, 'HalftimeAwayGoals': 0, 'Referee': 'BENNACEUR Ali (TUN)', 'Assistant1': 'ULLOA MORERA Berny (CRC)', 'Assistant2': 'DOTCHEV Bogdan (BUL)', 'RoundID': 714, 'MatchID': 392, 'HomeTeamInitials': 'ARG', 'AwayTeamInitials': 'ENG'}
{'_id': ObjectId('69cd0b1d5116547190fa1339'), 'Year': 1990, 'Stage': 'Quarter-finals', 'Stadium': 'Comunale', 'City': 'Florence ', 'HomeTeamName': 'Yugoslavia', 'HomeTeamGoals': 0, 'AwayTeamGoals': 0, 'AwayTeamName': 'Argentina', 'Attendance': 38971.0, 'HalftimeHomeGoals': 0, 'HalftimeAwayGoals': 0, 'Referee': 'ROETHLISBERGER Kurt (SUI)', 'Assistant1': 'JOUINI Neji (TUN)', 'Assistant2': 'HANSAL Mohamed (ALG)', 'RoundID': 751, 'MatchID': 31, 'HomeTeamInitials': 'YUG', 'AwayTeamInitials': 'ARG'}

In this query, the dataset is filtered to display only matches played in the quarter-final stage. This demonstrates how MongoDB can be used to retrieve specific records based on a given condition.

## Query 2: Projection (Selected Fields)

In [26]:
# Display only selected fields: Year, Stage, HomeTeamName, AwayTeamName
result = collection.find({}, {
    "Year": 1,
    "Stage": 1,
    "HomeTeamName": 1,
    "AwayTeamName": 1,
    "_id": 0
})

for doc in result.limit(10):
    print(doc)

{'Year': 1982, 'Stage': 'Group 6', 'HomeTeamName': 'Brazil', 'AwayTeamName': 'Soviet Union'}
{'Year': 1982, 'Stage': 'Group 3', 'HomeTeamName': 'Hungary', 'AwayTeamName': 'El Salvador'}
{'Year': 1982, 'Stage': 'Group 6', 'HomeTeamName': 'Scotland', 'AwayTeamName': 'New Zealand'}
{'Year': 1982, 'Stage': 'Group 2', 'HomeTeamName': 'Germany FR', 'AwayTeamName': 'Algeria'}
{'Year': 1982, 'Stage': 'Group 4', 'HomeTeamName': 'England', 'AwayTeamName': 'France'}
{'Year': 1982, 'Stage': 'Group 5', 'HomeTeamName': 'Spain', 'AwayTeamName': 'Honduras'}
{'Year': 1982, 'Stage': 'Group 4', 'HomeTeamName': 'Czechoslovakia', 'AwayTeamName': 'Kuwait'}
{'Year': 1982, 'Stage': 'Group 1', 'HomeTeamName': 'Italy', 'AwayTeamName': 'Peru'}
{'Year': 1982, 'Stage': 'Group 3', 'HomeTeamName': 'Argentina', 'AwayTeamName': 'Hungary'}
{'Year': 1982, 'Stage': 'Group 6', 'HomeTeamName': 'Brazil', 'AwayTeamName': 'Scotland'}

In this query, documents are filtered to display only quarter-final matches, and only selected fields such as Year, HomeTeamName, and AwayTeamName are retrieved. This demonstrates the use of projection in MongoDB to limit the returned data and improve query efficiency

## Query 3: Final matches

In [18]:
# Retrieve only key details for final matches
for doc in collection.find(
    {"Stage": "Final"},
    {"Year": 1, "HomeTeamName": 1, "AwayTeamName": 1, "HomeTeamGoals": 1, "AwayTeamGoals": 1, "_id": 0}
).limit(10):
    print(doc)

{'Year': 1982, 'HomeTeamName': 'Italy', 'HomeTeamGoals': 3, 'AwayTeamGoals': 1, 'AwayTeamName': 'Germany FR'}
{'Year': 1986, 'HomeTeamName': 'Argentina', 'HomeTeamGoals': 3, 'AwayTeamGoals': 2, 'AwayTeamName': 'Germany FR'}
{'Year': 1990, 'HomeTeamName': 'Germany FR', 'HomeTeamGoals': 1, 'AwayTeamGoals': 0, 'AwayTeamName': 'Argentina'}
{'Year': 1994, 'HomeTeamName': 'Brazil', 'HomeTeamGoals': 0, 'AwayTeamGoals': 0, 'AwayTeamName': 'Italy'}
{'Year': 1998, 'HomeTeamName': 'Brazil', 'HomeTeamGoals': 0, 'AwayTeamGoals': 3, 'AwayTeamName': 'France'}
{'Year': 2002, 'HomeTeamName': 'Germany', 'HomeTeamGoals': 0, 'AwayTeamGoals': 2, 'AwayTeamName': 'Brazil'}
{'Year': 2006, 'HomeTeamName': 'Italy', 'HomeTeamGoals': 1, 'AwayTeamGoals': 1, 'AwayTeamName': 'France'}
{'Year': 2010, 'HomeTeamName': 'Netherlands', 'HomeTeamGoals': 0, 'AwayTeamGoals': 1, 'AwayTeamName': 'Spain'}
{'Year': 2014, 'HomeTeamName': 'Germany', 'HomeTeamGoals': 1, 'AwayTeamGoals': 0, 'AwayTeamName': 'Argentina'}
{'Year': 2026, 'HomeTeamGoals': 3}

In [19]:
for doc in collection.find(
    {"Year": 2014, "Stage": "Final"},
    {"Year": 1, "HomeTeamName": 1, "AwayTeamName": 1, "MatchID": 1, "_id": 0}
):
    print(doc)

{'Year': 2014, 'HomeTeamName': 'Germany', 'AwayTeamName': 'Argentina', 'MatchID': 300186501}

## Query 4 (Delete operation)

In [20]:
# Count how many will be deleted
collection.count_documents({"HomeTeamGoals": 0})

140

In [21]:
# Delete all matches where HomeTeamGoals = 0
collection.delete_many({"HomeTeamGoals": 0})

print("Documents with HomeTeamGoals = 0 deleted")

Documents with HomeTeamGoals = 0 deleted

In [22]:
# Count how many will be deleted
collection.count_documents({"HomeTeamGoals": 0})

0

In this query, documents where the HomeTeamGoals value is equal to 0 are deleted from the collection. This demonstrates MongoDB’s ability to remove records based on a specified condition, supporting efficient data management and cleaning operations.

## Query 5 (Update operation)

In [23]:
# Count how many documents will be updated
collection.count_documents({"RoundID": 308})

26

In [24]:
# Update RoundID from 308 to 30800
collection.update_many(
    {"RoundID": 308},
    {"$set": {"RoundID": 30800}}
)

print("RoundID updated successfully")

RoundID updated successfully

In [25]:
# Confirm update worked
collection.count_documents({"RoundID": 30800})

26

In this query, documents with a specific RoundID value are updated to a new value using the update operation. This demonstrates MongoDB’s capability to modify existing records efficiently without the need to recreate the dataset